// Mock data for demo mode
export const mockUser = {
  id: 'demo-user-123',
  email: 'demo@example.com',
  created_at: '2024-01-01T00:00:00Z',
  subscription_plan: 'pro',
};

export const mockAudits = [
  {
    id: '1',
    domain: 'example.com',
    url: 'https://example.com',
    status: 'completed',
    health_score: 85,
    critical_issues: 2,
    warnings: 5,
    notices: 8,
    pages_crawled: 50,
    created_at: '2024-11-20T10:00:00Z',
    completed_at: '2024-11-20T10:15:00Z',
  },
  {
    id: '2',
    domain: 'demo-site.com',
    url: 'https://demo-site.com',
    status: 'completed',
    health_score: 72,
    critical_issues: 5,
    warnings: 12,
    notices: 15,
    pages_crawled: 25,
    created_at: '2024-11-19T14:30:00Z',
    completed_at: '2024-11-19T14:45:00Z',
  },
  {
    id: '3',
    domain: 'test-website.org',
    url: 'https://test-website.org',
    status: 'running',
    health_score: 0,
    critical_issues: 0,
    warnings: 0,
    notices: 0,
    pages_crawled: 15,
    created_at: '2024-11-20T15:00:00Z',
    completed_at: null,
  },
];

export const mockAuditDetails = {
  id: '1',
  domain: 'example.com',
  url: 'https://example.com',
  status: 'completed',
  health_score: 85,
  critical_issues: 2,
  warnings: 5,
  notices: 8,
  pages_crawled: 50,
  created_at: '2024-11-20T10:00:00Z',
  completed_at: '2024-11-20T10:15:00Z',
  lcp_score: 2.1,
  inp_score: 95,
  cls_score: 0.08,
  performance_score: 88,
};

export const mockIssues = [
  {
    id: '1',
    audit_id: '1',
    page_url: 'https://example.com',
    issue_type: 'missing_meta_description',
    severity: 'critical',
    message: 'Missing meta description',
    recommendation: 'Add a compelling meta description between 120-160 characters that includes your target keywords naturally.',
    element: '<head>',
    created_at: '2024-11-20T10:15:00Z',
  },
  {
    id: '2',
    audit_id: '1',
    page_url: 'https://example.com/about',
    issue_type: 'missing_h1',
    severity: 'critical',
    message: 'Missing H1 heading',
    recommendation: 'Add a single, descriptive H1 heading to every page that clearly indicates the page topic.',
    element: '<body>',
    created_at: '2024-11-20T10:15:00Z',
  },
  {
    id: '3',
    audit_id: '1',
    page_url: 'https://example.com/products',
    issue_type: 'slow_page_load',
    severity: 'warning',
    message: 'Page load time exceeds 3 seconds',
    recommendation: 'Optimize images, minify CSS/JS, enable browser caching, and consider using a CDN.',
    element: null,
    created_at: '2024-11-20T10:15:00Z',
  },
  {
    id: '4',
    audit_id: '1',
    page_url: 'https://example.com/blog',
    issue_type: 'duplicate_title',
    severity: 'warning',
    message: 'Duplicate title tag found',
    recommendation: 'Ensure each page has a unique title tag that accurately describes the page content.',
    element: '<title>Example Blog</title>',
    created_at: '2024-11-20T10:15:00Z',
  },
  {
    id: '5',
    audit_id: '1',
    page_url: 'https://example.com/contact',
    issue_type: 'missing_alt_text',
    severity: 'notice',
    message: '3 images missing alt text',
    recommendation: 'Add descriptive alt text to all images for accessibility and SEO benefits.',
    element: '<img src="/contact-hero.jpg">',
    created_at: '2024-11-20T10:15:00Z',
  },
];

export const mockProfile = {
  id: 'demo-user-123',
  email: 'demo@example.com',
  subscription_plan: 'pro',
  subscription_status: 'active',
  audits_this_month: 15,
  audits_limit: 100,
  created_at: '2024-01-01T00:00:00Z',
};
